--- 
id_field: 
  width: 200
app: 
  title: BITS Terminal
  height: 400
  width: 320
id_field_box: 
  width: 100%
main_flow: 
  margin: 10
  width: 100%
response_box: 
  width: 100%
main_stack: 
  width: 100%
person_details_box: 
  margin_top: 10
  width: 70%
note_box: 
  height: 200
  width: 300
note_box_box: 
  margin_top: 10
  width: 100%
